(ns parity.scaffold
  "Generate protocol stubs and type scaffolding from JVM host contract.

  Uses reflection data from parity.analyze.roots to emit:
    - defprotocol for each clojure.lang interface
    - Bridge function stubs for RT/Numbers/Util
    - Concrete type stubs (defrecord or TODO markers)

  Output is valid .cljc that compiles but throws 'not yet implemented'."
  (:require [clojure.string :as str]
            [clojure.java.io :as io]
            [parity.analyze.roots :as roots]))

;; =============================================================================
;; Method signature helpers
;; =============================================================================

(defn method-params
  "Generate param names for a method with given arity."
  [arity]
  (case (int arity)
    0 []
    1 ['a]
    2 ['a 'b]
    3 ['a 'b 'c]
    4 ['a 'b 'c 'd]
    (mapv #(symbol (str "a" %)) (range arity))))

(def java-interface-methods
  "Methods inherited from java.lang.Object or java.util interfaces, not Clojure."
  #{"equals" "hashCode" "toString" "getClass" "notify" "notifyAll" "wait"
    "forEach" "spliterator" "stream" "parallelStream" "toArray"
    "getAsBoolean" "getAsDouble" "getAsInt" "getAsLong" "get"
    "accept" "andThen" "compose" "identity" "run" "test"
    "apply" "compareTo" "iterator" "size" "isEmpty" "contains"
    "containsAll" "add" "addAll" "remove" "removeAll" "retainAll" "clear"
    "listIterator" "subList" "set" "indexOf" "lastIndexOf"})

(defn unique-methods
  "Deduplicate methods by name, keeping highest arity. Filter Java noise."
  [methods]
  (->> methods
       (remove #(java-interface-methods (:name %)))
       (group-by :name)
       (map (fn [[name ms]]
              (apply max-key :arity ms)))
       (sort-by :name)))

;; =============================================================================
;; Protocol generation
;; =============================================================================

(defn emit-protocol
  "Emit a defprotocol form string for an interface."
  [{:keys [name instance interfaces]}]
  (let [methods (unique-methods instance)
        extends (when (seq interfaces)
                  (str "  ;; extends: " (str/join ", " interfaces)))]
    (str "(defprotocol " name "\n"
         (when extends (str extends "\n"))
         (str/join "\n"
           (for [{:keys [name arity]} methods
                 :let [params (method-params arity)
                       all-params (into ['this] params)]]
             (str "  (" name " [" (str/join " " all-params) "])")))
         ")\n")))

;; =============================================================================
;; Bridge function stubs
;; =============================================================================

(defn emit-bridge-stubs
  "Emit function stubs for a bridge class (RT, Numbers, Util)."
  [class-name {:keys [ops]}]
  (let [prefix (case class-name
                 "RT" "rt-"
                 "Numbers" "num-"
                 "Util" "util-"
                 (str (str/lower-case class-name) "-"))]
    (str ";; " class-name " bridge (" (count ops) " ops)\n"
         (str/join "\n"
           (for [[method-name overload-count] (sort ops)]
             (str "(defn " prefix method-name " [& args] "
                  "(throw (ex-info \"not yet implemented: " class-name "/" method-name "\" {})))")))
         "\n")))

;; =============================================================================
;; Concrete type stubs
;; =============================================================================

(defn emit-type-stub
  "Emit a stub for a concrete type."
  [{:keys [name interfaces instance statics]}]
  (let [ifaces (when (seq interfaces)
                 (str "  ;; implements: " (str/join ", " interfaces)))]
    (str ";; " name " (" (count instance) " instance methods, "
         (count statics) " static)\n"
         (when ifaces (str ifaces "\n"))
         "(comment\n"
         "  (deftype " name " []\n"
         (str/join "\n"
           (for [iface interfaces]
             (str "    " iface)))
         "))\n")))

;; =============================================================================
;; Full scaffold
;; =============================================================================

(defn generate-scaffold
  "Generate the full scaffold from host contract. Returns string."
  []
  (let [host (roots/collect-host)
        ifaces (:interfaces host)
        concretes (:concretes host)
        bridge (:bridge host)]

    (str
      ";; =============================================================================\n"
      ";; Scaffold — generated by clojure.parity\n"
      ";;\n"
      ";; Protocol stubs, bridge functions, and type outlines for a Clojure runtime.\n"
      ";; Everything throws 'not yet implemented' — fill in the bodies.\n"
      ";;\n"
      ";; Generated from JVM reflection: "
      (count ifaces) " interfaces, "
      (reduce + (map :unique (vals bridge))) " bridge ops, "
      (count concretes) " concrete types\n"
      ";; =============================================================================\n\n"

      ";; =============================================================================\n"
      ";; Protocols (from clojure.lang interfaces)\n"
      ";; =============================================================================\n\n"
      (str/join "\n" (map emit-protocol ifaces))
      "\n"

      ";; =============================================================================\n"
      ";; Bridge functions (RT, Numbers, Util)\n"
      ";; =============================================================================\n\n"
      (str/join "\n" (for [[cn data] (sort bridge)]
                       (emit-bridge-stubs cn data)))
      "\n"

      ";; =============================================================================\n"
      ";; Concrete types (implement these)\n"
      ";; =============================================================================\n\n"
      (str/join "\n" (map emit-type-stub concretes)))))

(defn scaffold
  "Generate scaffold and write to file."
  [output-path]
  (let [content (generate-scaffold)]
    (io/make-parents output-path)
    (spit output-path content)
    (println (format "  Generated %s (%d lines)"
                     output-path (count (str/split-lines content))))))
